typography_spectrum: 0.7614566427655518
color:
  brandStrength: 0.8227861579507589
  lightness: 0.8849433015566319
  saturation: 0.5768568990752101
  rhythmicContrast: 0.7274773537646979
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
opengraph:
  image: null
  appId: ''
  type: 'https://www.facebook.com/marianne.gryu'
layout_spectrum: 0.29727744217962027
author:
  name: Marianne
  email: mariannegryu@gmail.com
  url: 'https://www.facebook.com/marianne.gryu'
name: Food me Marianne
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6371110d-d914-4ea1-aeb4-97edab5976bf.png
title: Food me Marianne
