typography_spectrum: 0.06615473236888647
color:
  brandStrength: 0.8338486202992499
  lightness: 0.28043747367337346
  saturation: 0.3106531072407961
  rhythmicContrast: 0.8880147859454155
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
opengraph:
  image: null
  appId: ''
  type: 'https://www.facebook.com/marianne.gryu'
layout_spectrum: 0.7492554686032236
author:
  name: Marianne
  email: mariannegryu@gmail.com
  url: 'https://www.facebook.com/marianne.gryu'
name: Food me Marianne
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6371110d-d914-4ea1-aeb4-97edab5976bf.png
title: Food me Marianne
