typography_spectrum: 0.2659767128061503
color:
  brandStrength: 0.6684027146548033
  lightness: 0.252987066982314
  saturation: 0.33150146715343
  rhythmicContrast: 0.9639792609959841
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
opengraph:
  image: null
  appId: ''
  type: 'https://www.facebook.com/marianne.gryu'
layout_spectrum: 0.44338865927420557
author:
  name: Marianne
  email: mariannegryu@gmail.com
  url: 'https://www.facebook.com/marianne.gryu'
name: Food me Marianne
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6371110d-d914-4ea1-aeb4-97edab5976bf.png
title: Food me Marianne
