typography_spectrum: 0.190131128532812
color:
  brandStrength: 0.2036026082932949
  lightness: 0.9246643220540136
  saturation: 0.5333665937650949
  rhythmicContrast: 0.6578924360219389
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
opengraph:
  image: null
  appId: ''
  type: 'https://www.facebook.com/marianne.gryu'
layout_spectrum: 0.44338865927420557
author:
  name: Marianne
  email: mariannegryu@gmail.com
  url: 'https://www.facebook.com/marianne.gryu'
name: Food me Marianne
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6371110d-d914-4ea1-aeb4-97edab5976bf.png
title: Food me Marianne
