typography_spectrum: 0.3203127169981599
color:
  brandStrength: 0.26349277701228857
  lightness: 0.9438738888129592
  saturation: 0.920843685278669
  rhythmicContrast: 0.9580337954685092
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
opengraph:
  image: null
  appId: ''
  type: 'https://www.facebook.com/marianne.gryu'
layout_spectrum: 0.31078532827086747
author:
  name: Marianne
  email: mariannegryu@gmail.com
  url: 'https://www.facebook.com/marianne.gryu'
name: Food me Marianne
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6371110d-d914-4ea1-aeb4-97edab5976bf.png
title: Food me Marianne
